---
sudo: false
language: rust
rust:
  - nightly

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash

addons:
  apt:
    packages:
      - gcc-multilib
